### ISSUE TITLE
Consider spacing to create logical groupings

### ISSUE THREAD

**Issue by abostroem** [Karthikprabhu22/MCMC#2]
https://github.com/Karthikprabhu22/MCMC/blob/71edd60b646db75a5efe5314ff9ec73cd1df2bc0/Bayesian.py#L26

This may be something that the formatter did. But if not, consider removing some spaces (e.g. in the exponent) to signify order of operations visually

**Comment by Karthikprabhu22** [comment]
This is something the formatter did.
