### ISSUE TITLE
uniform prior adds noise?

### ISSUE THREAD

**Issue by abostroem** [Karthikprabhu22/MCMC#3]
https://github.com/Karthikprabhu22/MCMC/blob/71edd60b646db75a5efe5314ff9ec73cd1df2bc0/Bayesian.py#L30

a uniform prior says that the likelihood of every value of a has equal probability (i.e. you don't think that one value is more likely to be right than another one. By drawing from a uniform distribution between 1 and 10 and then multiplying your likelihood by that value, you are randomly weighting values of a, which I think will cause the code to take longer to converge. A uniform prior is a constant (e.g. does not modify the likelihood).

**Comment by Karthikprabhu22** [comment]
I think that a uniform prior doesn't imply **a** can take any value on the real line with equal probability. It only means that **P(a)** is independent of **a** for a range that we choose. I feel like throwing out the prior will, in fact, increase the convergence time.

**Comment by abostroem** [comment]
In general, you are correct, a prior provide additional information about what you know the value of a parameter should be. However, another important aspect of the prior is that is should be deterministic. Your prior should not return a different value if you input the same value of the parameter. While you're prior, in general, restricts the parameter space to 1.7-3.7, within this parameter space, it stochastically assigns values, every time its called, even when that parameter value is the same.
