### ISSUE TITLE
Consider np.random.normal

### ISSUE THREAD

**Issue by abostroem** [Karthikprabhu22/MCMC#7]
https://github.com/Karthikprabhu22/MCMC/blob/71edd60b646db75a5efe5314ff9ec73cd1df2bc0/Bayesian.py#L105

i'm not sure what the overheads are of creating a norm object and then calculating rvs(). It may be faster and more direct/readable to use np.random.normal

**Comment by Karthikprabhu22** [comment]
Switched to NumPy rng.
